import 'package:flutter/material.dart';

/// ColorSchemes do Design System §3. O ESCURO é o tema padrão; o claro tem
/// paridade total. Nomes de token idênticos ao Claude Design (de-para direto).
abstract final class AppColorSchemes {
  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF6FDEB5),
    onPrimary: Color(0xFF003828),
    primaryContainer: Color(0xFF00513C),
    onPrimaryContainer: Color(0xFF93FBD0),
    secondary: Color(0xFFB8C4FF),
    onSecondary: Color(0xFF002B75),
    secondaryContainer: Color(0xFF0B409F),
    onSecondaryContainer: Color(0xFFDCE1FF),
    tertiary: Color(0xFFFBBE48),
    onTertiary: Color(0xFF402D00),
    tertiaryContainer: Color(0xFF5C4200),
    onTertiaryContainer: Color(0xFFFFDEAD),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0F1513),
    onSurface: Color(0xFFDFE4DE),
    onSurfaceVariant: Color(0xFFC0C9C0),
    surfaceContainerLowest: Color(0xFF0A0F0D),
    surfaceContainerLow: Color(0xFF171D1A),
    surfaceContainer: Color(0xFF1B211E),
    surfaceContainerHigh: Color(0xFF252B28),
    surfaceContainerHighest: Color(0xFF2F3633),
    outline: Color(0xFF8A938B),
    outlineVariant: Color(0xFF404943),
    inverseSurface: Color(0xFFDFE4DE),
    onInverseSurface: Color(0xFF2B312E),
    inversePrimary: Color(0xFF006C50),
    scrim: Color(0xFF000000),
    shadow: Color(0xFF000000),
  );

  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF006C50),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF93FBD0),
    onPrimaryContainer: Color(0xFF00201A),
    secondary: Color(0xFF2C57B8),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFDCE1FF),
    onSecondaryContainer: Color(0xFF00174B),
    tertiary: Color(0xFF7C5800),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFDEAD),
    onTertiaryContainer: Color(0xFF261900),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFF5FBF4),
    onSurface: Color(0xFF171D1A),
    onSurfaceVariant: Color(0xFF404943),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFEFF5ED),
    surfaceContainer: Color(0xFFE9F0E8),
    surfaceContainerHigh: Color(0xFFE4EAE2),
    surfaceContainerHighest: Color(0xFFDFE4DE),
    outline: Color(0xFF707972),
    outlineVariant: Color(0xFFC0C9C0),
    inverseSurface: Color(0xFF2B312E),
    onInverseSurface: Color(0xFFEFF5ED),
    inversePrimary: Color(0xFF6FDEB5),
    scrim: Color(0xFF000000),
    shadow: Color(0xFF000000),
  );
}
